trigger:
- dev
- master

pr:
- master


pool:
  vmImage: 'windows-latest'

variables:
  - group: 'Package Versioning'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration 
    value: 'Release'
  - name: buildDirPath 
    value: '$(Build.SourcesDirectory)\src\ReCaptcha\bin\$(buildPlatform)\$(buildConfiguration)'
  - name: packageVersion
    value: '$(major).$(minor).$(patch)'


jobs:
  - job: Init
    displayName: Initialize & Versioning
    steps:
      - task: PowerShell@2
        displayName: Set Development Version
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
        inputs:
          targetType: 'inline'
          script: |
            Write-Host  "##vso[task.LogIssue type=warning;]$(packageVersion)"
            Write-Host "##vso[task.setvariable variable=packageVersion;isOutput=true]$(packageVersion)-ci.$(Build.BuildId)"
            Write-Host  "##vso[task.LogIssue type=warning;]Expected: $(packageVersion)-ci.$(Build.BuildId)"
            Write-Host  "##vso[task.LogIssue type=warning;]Actuall: $(packageVersion)"

  - job: BuildPack
    displayName: Build & Pack
    dependsOn: Init
    steps:
    - task: MSBuild@1
      displayName: Build & Pack Project
      inputs:
        solution: '**/src/ReCaptcha/ReCaptcha.csproj'
        configuration: $(buildConfiguration)
        platform: $(buildPlatform)
        msbuildArguments: '/restore /t:Build /t:Pack /p:ContinuousIntegrationBuild=true /p:Deterministic=false /p:PackageVersion=$(packageVersion) /p:PackageOutputPath="$(buildDirPath)"'
        
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(buildDirPath)'
        ArtifactName: 'nuget'
        publishLocation: 'Container'

  - job: Test
    displayName: Run Unit Tests
    dependsOn: Init
    steps:
      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: 'test'
          publishTestResults: true
          projects: '**/tests/ReCaptcha.Tests/ReCaptcha.Tests.csproj'
          testRunTitle: 'Project Unit Tests'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

  - deployment: PushArtifacts
    displayName: Push to Development Feed
    dependsOn: 
      - BuildPack
      - Test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: nuget
          
            - task: NuGetCommand@2
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: '664acd3b-eaa2-47d0-a9a4-09c7e2741d7d'
                allowPackageConflicts: true