trigger:
  branches:
    include:
    - dev
    - master
  paths:
    exclude:
    - '*/README.md'


pool:
  vmImage: 'windows-latest'

variables:
  - group: 'Package Versioning'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration 
    value: 'Release'
  - name: buildDirPath 
    value: '$(Build.SourcesDirectory)\src\ReCaptcha\bin\$(buildPlatform)\$(buildConfiguration)'


jobs:
  - job: Init
    displayName: Initialize & Versioning
    steps:

      - powershell: | 
          if('$(Build.SourceBranch)' -eq 'refs/heads/master')
          {
            Write-Host "##vso[task.setvariable variable=version;isOutput=true]$(major).$(minor).$(patch)"
          }
          else
          {
            Write-Host "##vso[task.setvariable variable=version;isOutput=true]$(major).$(minor).$(patch)-ci$(Build.BuildId)"
          }
        displayName: Set Package Version
        name: package

  - job: BuildPack
    displayName: Build & Pack
    dependsOn: Init
    variables:
      - name: packageVersion
        value: $[ dependencies.Init.outputs['package.version'] ]
    steps:
    - task: MSBuild@1
      displayName: Build & Pack Project
      inputs:
        solution: '**/src/ReCaptcha/ReCaptcha.csproj'
        configuration: $(buildConfiguration)
        platform: $(buildPlatform)
        msbuildArguments: '/restore /t:Build /t:Pack /p:ContinuousIntegrationBuild=true /p:Deterministic=false /p:PackageVersion=$(packageVersion) /p:PackageOutputPath="$(buildDirPath)"'
        
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(buildDirPath)'
        ArtifactName: 'nuget'
        publishLocation: 'Container'

  - job: Test
    displayName: Run Unit Tests
    dependsOn: Init
    steps:
      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: 'test'
          publishTestResults: true
          projects: '**/tests/ReCaptcha.Tests/ReCaptcha.Tests.csproj'
          testRunTitle: 'Project Unit Tests'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

  - deployment: PushArtifacts
    displayName: Push to Development Feed
    dependsOn: 
      - BuildPack
      - Test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: nuget
          
            - task: NuGetCommand@2
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: 'f9036ec9-eb1c-4aff-a2b8-27fdaa573d0f/29b705d0-eac8-42a7-9230-4bcfe9f83688'
                allowPackageConflicts: true

            - task: DownloadFile@1
              displayName: 'Download version bump script'
              inputs:
                FileUrl: 'https://gist.githubusercontent.com/jooni91/d3e5ca575402eb3454dd1c1a4a4d998e/raw/d13c90d62ad0d614df9c5129c47a51c19e9460cb/update-patch-version-code-script.ps1'

            - task: PowerShell@2
              displayName: 'Run version bump script'
              inputs:
                targetType: filePath
                filePath: './update-version-code-script.ps1'
                arguments: '$(System.AccessToken)'
